--- !map:HashWithIndifferentAccess 
general: !map:HashWithIndifferentAccess 
  parentskin: 
gmtv: !map:HashWithIndifferentAccess 
  default_channel_id: 
google_ads_bottom: !map:HashWithIndifferentAccess 
  google_color_text: DDDDDD
  google_alternate_color: ffffff
  google_color_url: 008000
  google_color_border: ffffff
  google_color_bg: ffffff
  google_color_link: AD0011
google_ads: !map:HashWithIndifferentAccess 
  google_color_text: a0a0a0
  google_alternate_color: ffffff
  google_color_url: 008000
  google_color_border: ffffff
  google_color_bg: fafafa
  google_color_link: AD0011
