development:
  adapter: postgresql
  database: gamersmafia
  host: localhost
  username: postgres
  password:
  client_min_messages: warning

test:
  adapter: postgresql
  database: gamersmafia_test
  host: localhost
  username: postgres
  password:
  client_min_messages: warning

production:
  adapter: postgresql
  database: gamersmafia
  host: localhost
  username: postgres
  password:
  client_min_messages: warning

support:
  adapter: postgresql
  database: gamersmafia_replicated
  host: tachikoma.slnc.net
  username: postgres
  password: ic4ro69
  client_min_messages: warning
