development:
  adapter: postgresql
  database: gamersmafia
  host: localhost
  username: postgres
  password:
  client_min_messages: warning

production:
  adapter: postgresql
  database: gamersmafia
  host: localhost
  username: postgres
  password:
  client_min_messages: warning

test:
  adapter: postgresql
  database: gamersmafia_test
  host: localhost
  username: postgres
  password:
  client_min_messages: warning
