general:
  parentskin: 

google_colours:
  google_color_border: "FFFFFF"
  google_color_bg: "FFFFFF"
  google_alternate_color: "FFFFFF"
  google_color_link: "AD0011"
  google_color_url: "008000"
  google_color_text: "DDDDDD"

gmtv:
  default_channel_id: 
