attributes:
    base_color_value:
       name: "Color"
       type: RgbColor
       default_color_gen_hint: css_body_bg
    
    lightness:
       name: "Claridad"
       type: Percent
       default_color_gen_hint: css_body_bg
     
    contrast:
       name: "Contraste"
       type: Percent
       default_color_gen_hint: css_body_bg