general:
  parentskin: clan_default
  intelliskin: true
  
intelliskin:
  lycolumns: "3"
  lyside: left
  modules_right: 
  - clan/poll
  - clan/members
  - clan/visitas
  - clan/events
  - clan/last_gm_matches
  - clan/next_gm_matches
  - clan/randomimg
  - clan/friends
  modules_left: 
  - online
  - sponsors
  - webchat
  - last_commented_objects
  - tracker
  page_width: "984"
  sidebar_position: left
  color_gen: BlackSpot

    
  BlackSpot: !map:HashWithIndifferentAccess 
    color_gen_params: !map:HashWithIndifferentAccess 
      hue: "60"